name: nid_data_fetch
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_ml_kit: ^0.16.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  image_picker: ^1.0.7

dependencies_override:
  google_mlkit_smart_reply: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/nid.json

